version: "3.9"

services:
  prestashop:
    image: jkrupiniewicz/be-toys4boys:0.1.2
    ports:
      - "18885:443"
    #depends_on:
    #  - memcached
    environment:
      DB_USER: "root"
      DB_PASSWD: "student"
      DB_SERVER: "admin-mysql_db"
      DB_HOST: "admin-mysql_db"
      DB_NAME: "BE_188857"
      PS_DOMAIN: "localhost:18885"
      PS_INSTALL_AUTO: 0
      MEMCACHED_SERVER: "memcached"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
      resources:
        limits:
          cpus: "0.5"
    networks:
      - admin-mysql_default
      - prestashop_network

  memcached:
    image: memcached:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: "0.5"
    networks:
      - admin-mysql_default
      - prestashop_network

networks:
  prestashop_network:
  admin-mysql_default:
    external: true
